import { css } from '@emotion/react';

export const styles = {
  container: css`
    display: flex;
  `,
  iconLink: css`
    margin: 5px 15px;
  `,
  icon: css`
    &:hover {
      // filter generated by https://pranjaldubey.com/css-filter-generator/
      filter: invert(50%) sepia(50%) saturate(3858%) hue-rotate(315deg) brightness(88%) contrast(85%);
    }
  `
};
